- name: variables from  files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: printing the variables
    ansible.builtin.debug
      msg: "i am learning {{NAME}}, duration is:{{DURATION}}, triner is:{{TRAINER}}"