- name: variables feom task level
  hosts: localhost
  vars:
    money: "10000 RS"
    land:  "100 hectors"
  tasks:
  - name: inherite the   value from play level
    ansible.builtin.debug:
    msg: "MONEY: {{money}}, land: {{land}}"
  - name: inheriate the values from play level and add and override
    vars:
     money: "20000 RS"
     houses: "3"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"
