- name: create user
  hosts: localhost
  tasks:
  - name: chek roboshop username exit or not
    ansible.builtin.command: id roboshop
    register: output
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"