- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
     - nginx
     - postfix
     - mailx